Added axis type to Recharts.lean, modified Plot.lean to illustrate.
leanprover-community/ProofWidgets4 pull request #99
Opened 2024-12-23 17:47 UTC by mars0i

This PR adds `AxisType` to Recharts.lean, and sets its default value to `.number` (rather than `.category`, which would be the default inherited from Recharts).  This change will affect all existing uses of `<XAxis ...>` or `<YAxis ...>`.  See #98 for notes on what difference this makes, and why `.number` seems like a better default for Lean.  The old behavior can be restored by adding `type={.category}` to `<XAxis ...>`, or `<YAxis ...>` if it represents the independent variable.

In Plot.lean I modified the existing `Plot` example so that it clearly illustrates the effects of `type={.number}`.  The docstring suggests changing that to `type={.category}` to see the difference.

I forked mathlib and built it on my computer using the modified ProofWidgets4 (using this temporary [lakefile.lean](https://github.com/mars0i/mathlib4/blob/ProofWidgetsRechartAxisType/lakefile.lean)).  I used that to test in a project of mine.  

Do I need to run mathlib through CI before this PR can get accepted?  I can ask for write access and do that, but I'm not it would be appropriate appropriate to send a PR of a mathlib branch that points to my personal copy of ProofWidgets4.

(I did get an error after `lake udpate` in mathlib when I ran `lake exe cache get`, but I assume that was because I was pointing to my copies of mathlib and ProofWidgets4.  Not sure how `lake exe cache get` works.)

2024-12-23 22:41 UTC, mars0i commented
Contrary to what I said, my own project is _not_ pulling in my version of ProofWidgets4 via my version of mathlib. Not sure why. Not sure whether this is a reason not to accept the PR, but I prefer to know that it works as an external library in a project.

2024-12-29 00:14 UTC, mars0i commented
I may continue to try to get `leanprover/mathlib` to [build with a reference to](https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/How.20to.20use.20my.20own.20version.20of.20ProofWidgets.20with.20Mathlib.3F/near/490081442) `mars0i/ProofWidgets4 @ RechartsAxisType`, but based on what you've said @Vtec234 and what I think I understand, I don't think there's a need to wait for that to succeed in order to accept this PR.  There may be other reasons to reject it, of course. I'm not sure, for example, whether the changes I made to `Plot` in `Demos/Plot.lean` will seem OK.

2025-01-14 11:13 UTC, Vtec234 commented on ProofWidgets/Component/Recharts.lean
> +  | category   -- Treat values as categorical: spaces between values are equal.
```suggestion
  /-- Treat values as numbers: spacing on axis by numeric difference. -/
  | number
  /-- Treat values as categorical: equal spacing between values. -/
  | category
```

2025-01-14 11:14 UTC, Vtec234 commented on ProofWidgets/Component/Recharts.lean
> +  type : AxisType := .number -- The Recharts default is category.
```suggestion
  /-- How values along this axis should be interpreted.
  The Recharts default is `category`. -/
  type : AxisType := .number
```

2025-01-14 11:24 UTC, Vtec234 requested changes
Thanks for the PR! The changes to `Recharts.lean` look good. As for `Plot.lean`, the purpose of the first demo there is just to demonstrate how to plot something, so I don't think we want to get into details of axis types there. How about leaving that demo as-is, and adding another section below illustrating a plot with some categorical data? Or, you could just leave `Plot.lean` entirely unchanged: just having the new default axis type would be helpful.

2025-01-14 11:25 UTC, Vtec234 commented on lakefile.lean
> +  -- releaseRepo := "https://github.com/leanprover-community/ProofWidgets4"
Please undo this change on this branch (for experimenting with different cloud release links, I would recommend having another branch which is not a PR branch).

2025-01-14 21:26 UTC, mars0i commented
I guess it would be fine to leave the plot example as is.  In the previous version, without `AxisType` defaulting to `.number`, I felt that the example was potentially misleading (it mislead me), since it hid the fact that unevenly spaced $x$ values would be treated as evenly spaced. But now ProofWidgets4 does the right thing by default--i.e. what would be expected by people doing mathematics--so there will be no surprises.  Someone who wants to can investigate `.categorical` can do do.

2025-01-14 21:27 UTC, mars0i commented
Might take me a few days to get back into the head space for this.

2025-01-14 22:24 UTC, Vtec234 commented
Don't worry about it, I can also just make the proposed changes myself and then merge :) Thanks for your help!

2025-01-15 10:30 UTC, merged

2025-01-15 21:09 UTC, mars0i commented
> Don't worry about it, I can also just make the proposed changes myself and then merge :) Thanks for your help!

Thanks very nice of you to complete it for me.  Glad I could help in a small way.